name: CI
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  commit:
    name: Commits
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stevearc/nvim-typecheck-action@v1
        with:
          path: lua
          level: Information
          configpath: ".luarc.json"
          neodev-version: stable
      - uses: cargo-bins/cargo-binstall@main
      - name: Selene
        run: |
          cargo binstall --no-confirm selene
          selene --config selene.toml ./lua
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --config-path .stylua.toml ./lua ./spec
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
        with:
          commit_message: "chore(pr): auto-commit"
          push_options: "--force"
  windows_unit_test:
    name: Windows Tests
    needs:
      - lint
    strategy:
      matrix:
        nvim_version: [stable]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: notomo/action-setup-nvim-lua@v1
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Run Tests
        run: |
          luarocks --lua-version=5.1 install vusted
          vusted ./spec
  unix_unit_test:
    name: Unix Tests
    needs:
      - lint
    strategy:
      matrix:
        nvim_version: [stable, nightly, v0.7.0]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Run Tests
        run: |
          luarocks install vusted
          vusted --shuffle ./spec
  code_coverage:
    name: Code Coverage
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: stable
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Run Tests
        run: |
          luarocks install luacov
          luarocks install vusted
          vusted --coverage ./spec
      - name: Generate Coverage Report
        run: |
          echo "ls ."
          ls -l .
          echo "run luacov"
          luacov
          echo "ls ."
          ls -l .
          echo "cat ./luacov.report.out"
          cat ./luacov.report.out
      - uses: codecov/codecov-action@v3
        with:
          files: luacov.report.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    needs:
      - unix_unit_test
      - code_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: traces.nvim
      - uses: actions/checkout@v4
      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Current stable release: ${{ steps.release.outputs.tag_name }}"
          tag_exists_error: false
          force_push_tag: true
      - uses: nvim-neorocks/luarocks-tag-release@v5
        if: ${{ steps.release.outputs.release_created }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: traces.nvim
          version: ${{ steps.release.outputs.tag_name }}
          labels: |
            neovim
            vim
